/* Hub Pessoal - academia.js
   Reformula a seção Academia: boneco muscular SVG interativo, navegação inferior (Início/Treinos/Exercícios/Progresso/Perfil).
   Carregar DEPOIS de corrida.js. Reaproveita S, A, UI, P, render, sv, chart (index.html) e preserva fichas, séries, descanso e sincronização.
   Dados extras ficam em S.use.gym (chave "use" já sincronizada). Nenhuma dependência externa. */
(()=>{
const LB={peito:'Peito',ombros:'Ombros',biceps:'Bíceps',triceps:'Tríceps',antebraco:'Antebraço',abdomen:'Abdômen',quadriceps:'Quadríceps',panturrilha:'Panturrilha',trapezio:'Trapézio',dorsais:'Costas',lombar:'Lombar',gluteos:'Glúteos',posteriores:'Posteriores'};
const RU=[[/triceps|testa|frances|paralela|mergulho|pushdown/,'triceps'],[/antebraco|punho/,'antebraco'],[/rosca|biceps|martelo/,'biceps'],[/abdominal|prancha|infra|crunch|abdomen|elevacao de pernas/,'abdomen'],[/lombar|hiperextensao|good morning|bom dia/,'lombar'],[/gluteo|hip thrust|pelvica|coice|abdutora/,'gluteos'],[/stiff|flexora|romeno|posterior|levantamento terra|^terra/,'posteriores'],[/agachamento|leg press|extensora|afundo|passada|hack|avanco|bulgaro|quadriceps/,'quadriceps'],[/panturrilha|gemeos|soleo/,'panturrilha'],[/encolhimento|trapezio/,'trapezio'],[/desenvolvimento|elevacao lateral|elevacao frontal|ombro|arnold|militar|face pull/,'ombros'],[/puxada|remada|barra fixa|pulldown|serrote|dorsal/,'dorsais'],[/supino|crucifixo|peck|voador|fly|flexao|crossover|peitoral/,'peito']];
const LIB=['Supino reto','Supino inclinado','Crucifixo','Flexão de braço','Puxada frontal','Remada curvada','Remada baixa','Barra fixa','Desenvolvimento com halteres','Elevação lateral','Encolhimento','Rosca direta','Rosca martelo','Tríceps corda','Tríceps testa','Mergulho nas paralelas','Rosca de punho','Abdominal','Prancha','Elevação de pernas','Hiperextensão lombar','Agachamento livre','Leg press','Cadeira extensora','Afundo','Mesa flexora','Stiff','Levantamento terra','Hip thrust','Panturrilha em pé'];
const TABS=[['ini','home','Início'],['trn','dumbbell','Treinos'],['exe','search','Exercícios'],['pro','chart','Progresso'],['per','sliders','Perfil']];
let tq='',gt='ini',gm=null,gv='f',xq='',xf='',px='';
const nm=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const gmap=()=>(S.use&&S.use.gym&&S.use.gym.map)||{};
const grp=n=>{const m=gmap();if(m[n])return m[n];const x=nm(n);for(const r of RU)if(r[0].test(x))return r[1];return null};
const dd=d=>Math.round((new Date(TD()+'T12:00')-new Date(d+'T12:00'))/864e5);
const fdt=d=>d.split('-').reverse().slice(0,2).join('/');
const hist=n=>S.workouts.map(w=>{const e=w.ex.find(x=>x.n==n);return e&&e.sets.length?{date:w.date,sets:e.sets}:null}).filter(Boolean);
const last=n=>hist(n).at(-1);
const top=h=>Math.max(...h.sets.map(x=>+x.l));
const lastDates=()=>{const o={};S.workouts.forEach(w=>w.ex.forEach(e=>{const g=e.sets.length&&grp(e.n);if(g&&(!o[g]||w.date>o[g]))o[g]=w.date}));return o};
const stt=(g,o)=>!o[g]?'unk':dd(o[g])<=1?'rec':dd(o[g])<=4?'ok':'idle';
const names=()=>[...new Set([...S.plans.flatMap(p=>p.ex.map(e=>e.n)),...S.workouts.flatMap(w=>w.ex.map(e=>e.n))])];
const allNames=()=>[...new Set([...names(),...LIB])].sort((a,b)=>a.localeCompare(b,'pt'));
const sets=s=>s.map(x=>x.l+'kg×'+x.r).join(', ');

/* ---- Boneco (desenho vetorial próprio, sem licença de terceiros). Cada caminho é a metade esquerda; é espelhado. ---- */
const FR=[['ombros','M30 37C23 39 18 45 17 54C16 58 17 62 19 64C23 63 26 59 28 54C29 48 31 42 36 38Z'],['peito','M49 40L37 39C33 41 30 46 30 52C32 58 38 61 44 60C47 59 49 58 49 57Z'],['biceps','M19 66C17 72 16 78 17 84C20 86 24 85 26 82C27 76 27 70 27 64C24 65 21 66 19 66Z'],['antebraco','M16 88C14 95 12 100 10 106L15 108C19 104 22 97 25 89C23 90 19 90 16 88Z'],['abdomen','M49 62L38 63C37 72 37 82 39 94L49 98Z'],['abdomen','M38 63C35 70 34 82 35 92L39 94C37 82 37 72 38 63Z'],['quadriceps','M48 104L38 102C34 112 32 126 33 140C35 144 41 145 46 142C48 132 49 118 48 104Z'],['panturrilha','M34 150C32 160 32 170 34 180C37 181 41 180 43 178C45 168 45 158 44 150C41 152 37 152 34 150Z']];
const BK=[['trapezio','M49 26L44 29C40 33 36 36 31 38C35 44 42 52 49 58Z'],['ombros','M30 37C23 39 18 45 17 54C16 58 17 62 19 64C23 63 26 59 28 54C29 48 31 42 36 38Z'],['dorsais','M49 60C43 56 37 50 32 42C30 52 31 64 35 74C39 78 45 76 49 74Z'],['triceps','M19 62C17 70 16 78 17 86C20 88 24 87 26 84C27 76 27 68 27 62C24 63 21 63 19 62Z'],['antebraco','M16 88C14 95 12 100 10 106L15 108C19 104 22 97 25 89C23 90 19 90 16 88Z'],['lombar','M49 76L39 78C39 84 40 90 43 94L49 94Z'],['gluteos','M49 96L35 96C32 102 32 110 35 116C40 118 46 116 49 112Z'],['posteriores','M48 118L35 118C33 128 33 138 35 146C40 148 45 146 47 144C48 136 48 126 48 118Z'],['panturrilha','M34 152C32 162 32 170 34 180C37 181 41 180 43 178C45 168 45 160 44 152C41 154 37 154 34 152Z']];
const DT={f:'M49 40V98M39 73H49M38 83H49M38 92H49M40 106C40 120 41 132 42 140',b:'M49 26V96M33 44C37 56 38 64 36 72'};
const BASE='M50 22L45 23L44 30C40 32 33 33 28 36C22 38 18 44 17 54C16 64 14 76 12 90C11 97 9 102 8 106L10 110L16 108L20 104C22 96 25 86 27 76C29 70 31 66 33 62C34 72 35 82 35 92C33 100 32 108 32 118C32 130 33 140 33 150C32 162 32 172 32 182L30 190L34 193L44 193L45 186C46 172 47 158 47 148C48 134 49 120 50 108Z';
const MIR='transform="translate(100 0) scale(-1 1)"';
const body=(v,o)=>`<svg class="bv${v==gv?' on':''}" viewBox="0 0 100 196" role=group aria-label="${v=='f'?'Frente':'Costas'}"><path class=bb d="${BASE}"/><path class=bb ${MIR} d="${BASE}"/><ellipse class=bb cx=50 cy=11 rx=7.5 ry=9.5 />${(v=='f'?FR:BK).map(([g,d])=>`<g class="mz ${stt(g,o)}${gm==g?' sel':''}" tabindex=0 role=button aria-label="${LB[g]}" onclick="G.m('${g}')" onkeydown="if(event.key=='Enter'||event.key==' '){event.preventDefault();G.m('${g}')}"><path d="${d}"/><path ${MIR} d="${d}"/></g>`).join('')}<path class=dt d="${DT[v]}"/><path class=dt ${MIR} d="${DT[v]}"/></svg>`;
const figure=o=>`<div class=bf><div class="row chips bt"><span class="ch ${gv=='f'?'on':''}" onclick="G.v('f')">Frente</span><span class="ch ${gv=='b'?'on':''}" onclick="G.v('b')">Costas</span></div><div class=bw>${body('f',o)}${body('b',o)}</div><div class=lg><span><i class=u></i>Sem registro</span><span><i class=r></i>Trabalhado há menos de 2 dias</span><span><i class=k></i>2 a 4 dias</span><span><i class=d></i>Mais de 4 dias</span></div><p class=s>Estimativa simples baseada nos treinos que você registrou.</p></div>`;

/* ---- Painel do músculo selecionado ---- */
const panel=o=>{if(!gm)return`<div class=em>${UI.i('target')}<p>Toque em um músculo para ver exercícios e histórico.</p></div>`;
const st=stt(gm,o),tx={unk:'Estado desconhecido: nenhum treino registrado para este grupo.',rec:'Treinado há '+dd(o[gm])+' dia(s). Pode precisar de mais recuperação.',ok:'Treinado há '+dd(o[gm])+' dias.',idle:'Último treino há '+dd(o[gm])+' dias.'}[st];
const ns=names().filter(n=>grp(n)==gm),hs=S.workouts.filter(w=>w.ex.some(e=>e.sets.length&&grp(e.n)==gm)).slice(-5).reverse();
return`<h3 style="margin-bottom:4px">${LB[gm]}</h3><p class=s>${tx}</p><div class=mt>${ns.map(n=>{const l=last(n);return`<div class=r><span class=f>${esc(n)}</span><span class=s>${l?fdt(l.date)+' · '+sets(l.sets):'sem registro'}</span></div>`}).join('')||`<p class=s>Nenhum exercício seu usa este grupo ainda. Associe exercícios no Perfil.</p>`}</div>${hs.length?`<h2 class=mt>Histórico</h2>${hs.map(w=>`<div class=r><span class=f>${esc(w.name)}</span><span class=s>${fdt(w.date)} · ${w.ex.filter(e=>e.sets.length&&grp(e.n)==gm).map(e=>esc(e.n)).join(', ')}</span></div>`).join('')}`:''}`};

/* ---- Telas ---- */
const planNext=()=>S.plans.length?S.plans[S.workouts.length%S.plans.length]:null;
const ini=()=>{const o=lastDates(),h=new Date().getHours(),pl=planNext(),lw=S.workouts.at(-1),w7=S.workouts.filter(w=>dd(w.date)<7).length,w30=S.workouts.filter(w=>dd(w.date)<30).length,rec=Object.keys(o).filter(g=>stt(g,o)!='idle').sort((a,b)=>o[b].localeCompare(o[a]));
return`<div class=ph><div><h1>${h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}${S.name?', '+esc(S.name):''}</h1><div class=sub>Academia</div></div></div>
<div class="c hero"><div class=s>Treino recomendado</div>${pl?`<h2 style="font-size:20px;margin:4px 0">${esc(pl.name)}</h2><p class=s>${pl.ex.map(e=>esc(e.n)).join(' · ')}</p><button class="b big2 mt" onclick="A.ws('${pl.id}')">${UI.i('play')}Iniciar treino</button>`:`<p class=s style="margin:6px 0">Crie uma ficha para ter um treino recomendado.</p><button class="b mt" onclick="G.t('trn')">${UI.i('plus')}Criar ficha</button>`}</div>
<div class="g2 two mt"><div class=c>${UI.ct('Mapa muscular')}${figure(o)}</div><div class=stk><div class=c>${panel(o)}</div>
<div class=c>${UI.ct('Treinados recentemente')}<div class=row>${rec.map(g=>`<span class="ch ${gm==g?'on':''}" onclick="G.m('${g}')">${LB[g]} · ${dd(o[g])==0?'hoje':dd(o[g])+'d'}</span>`).join('')||'<span class=s>Nada registrado nos últimos dias.</span>'}</div></div></div></div>
<div class=g2 style="margin-top:12px"><div class=c>${UI.ct('Último treino')}${lw?`<p><b>${esc(lw.name)}</b> <span class=s>${fdt(lw.date)} · ${fd(lw.sec)}</span></p>${lw.ex.map(e=>`<div class=s>${esc(e.n)}: ${sets(e.sets)||'—'}</div>`).join('')}`:UI.em('clock','Nenhum treino registrado.')}</div>
<div class=c>${UI.ct('Evolução')}<div class=stats><div><b>${w7}</b><span>treinos em 7 dias</span></div><div><b>${w30}</b><span>treinos em 30 dias</span></div><div><b>${S.workouts.length}</b><span>treinos no total</span></div><div><b>${prs().length}</b><span>recordes</span></div></div><button class="b g sm mt" onclick="G.t('pro')">Ver progresso</button></div>
<div class=c>${UI.ct('Fichas')}${S.plans.map(p=>`<div class=r><span class=f>${esc(p.name)}</span><button class="b sm" onclick="A.ws('${p.id}')">Começar</button></div>`).join('')||UI.em('dumbbell','Nenhuma ficha.')}</div></div>`};


/* ---- Biblioteca de treinos prontos (modelos de referência; viram fichas suas ao adicionar) ---- */
const D=(n,s)=>[n,s.split(';').map(x=>{const m=x.trim().match(/^(.*) (\d+)x(\d+)$/);return{n:m[1],s:+m[2],r:+m[3]}})];
const TPL=[
{t:'Full Body',f:'3 dias/sem',tg:['Iniciante','Academia'],d:'Corpo inteiro em cada treino. Ótimo para começar ou treinar pouco.',days:[D('A','Agachamento livre 3x10;Supino reto 3x10;Remada baixa 3x10;Desenvolvimento com halteres 3x10;Abdominal 3x15'),D('B','Leg press 3x12;Supino inclinado 3x10;Puxada frontal 3x10;Elevação lateral 3x12;Rosca direta 3x12'),D('C','Levantamento terra 3x8;Flexão de braço 3x10;Remada curvada 3x10;Afundo 3x10;Tríceps corda 3x12')]},
{t:'Superior/Inferior',f:'4 dias/sem',tg:['Intermediário','Academia'],d:'Alterna parte de cima e de baixo do corpo.',days:[D('Superior A','Supino reto 4x8;Remada curvada 4x8;Desenvolvimento com halteres 3x10;Rosca direta 3x10;Tríceps testa 3x10'),D('Inferior A','Agachamento livre 4x8;Stiff 3x10;Leg press 3x12;Mesa flexora 3x12;Panturrilha em pé 4x15'),D('Superior B','Supino inclinado 4x10;Puxada frontal 4x10;Elevação lateral 3x15;Rosca martelo 3x12;Tríceps corda 3x12'),D('Inferior B','Levantamento terra 4x6;Afundo 3x10;Cadeira extensora 3x12;Hip thrust 3x10;Panturrilha sentado 4x15')]},
{t:'ABC Clássico',f:'3 dias/sem',tg:['Intermediário','Academia'],d:'Três treinos divididos por grupos musculares.',days:[D('A · Peito e Tríceps','Supino reto 4x8;Supino inclinado 3x10;Crucifixo 3x12;Tríceps testa 3x10;Tríceps corda 3x12'),D('B · Costas e Bíceps','Puxada frontal 4x10;Remada curvada 4x8;Remada baixa 3x10;Rosca direta 3x10;Rosca martelo 3x12'),D('C · Pernas e Ombros','Agachamento livre 4x8;Leg press 3x12;Mesa flexora 3x12;Desenvolvimento com halteres 3x10;Elevação lateral 3x15')]},
{t:'ABCD',f:'4 dias/sem',tg:['Intermediário','Academia'],d:'Quatro dias com mais volume por grupo muscular.',days:[D('A · Peito','Supino reto 4x8;Supino inclinado 4x10;Crucifixo 3x12;Flexão de braço 3x15'),D('B · Costas','Barra fixa 4x8;Remada curvada 4x8;Puxada frontal 3x10;Remada baixa 3x12'),D('C · Pernas','Agachamento livre 4x8;Leg press 4x12;Cadeira extensora 3x12;Mesa flexora 3x12;Panturrilha em pé 4x15'),D('D · Ombros e Braços','Desenvolvimento com halteres 4x10;Elevação lateral 4x15;Rosca direta 3x10;Tríceps corda 3x12;Rosca martelo 3x12')]},
{t:'ABCDE',f:'5 dias/sem',tg:['Avançado','Academia'],d:'Um foco por dia, alto volume.',days:[D('A · Peito','Supino reto 5x8;Supino inclinado 4x10;Crucifixo 3x12;Crossover 3x15'),D('B · Costas','Barra fixa 4x8;Remada curvada 4x8;Puxada frontal 4x10;Remada baixa 3x12;Encolhimento 3x12'),D('C · Pernas','Agachamento livre 5x8;Leg press 4x12;Cadeira extensora 4x12;Afundo 3x10;Panturrilha em pé 4x15'),D('D · Ombros','Desenvolvimento com halteres 4x10;Elevação lateral 4x15;Elevação frontal 3x12;Face pull 3x15'),D('E · Braços e Abdômen','Rosca direta 4x10;Tríceps testa 4x10;Rosca martelo 3x12;Tríceps corda 3x12;Abdominal 4x20')]},
{t:'Push/Pull/Legs',f:'3 ou 6 dias/sem',tg:['Intermediário','Academia'],d:'Empurrar, puxar e pernas. Repita o ciclo para 6 dias.',days:[D('Push','Supino reto 4x8;Desenvolvimento com halteres 3x10;Supino inclinado 3x10;Elevação lateral 3x15;Tríceps corda 3x12'),D('Pull','Barra fixa 4x8;Remada curvada 4x8;Puxada frontal 3x10;Face pull 3x15;Rosca direta 3x10'),D('Legs','Agachamento livre 4x8;Stiff 3x10;Leg press 3x12;Mesa flexora 3x12;Panturrilha em pé 4x15')]},
{t:'Glúteos e Pernas',f:'3 dias/sem',tg:['Intermediário','Academia'],d:'Ênfase em glúteos, posteriores e quadríceps.',days:[D('A · Glúteos','Hip thrust 4x10;Elevação pélvica 3x12;Cadeira abdutora 3x15;Coice na polia 3x12;Afundo 3x10'),D('B · Posterior e Quadríceps','Stiff 4x10;Mesa flexora 3x12;Agachamento búlgaro 3x10;Leg press 3x12;Panturrilha em pé 4x15'),D('C · Glúteos e Core','Agachamento livre 4x10;Hip thrust 4x10;Passada 3x12;Abdominal infra 3x15')]},
{t:'Em Casa sem Equipamento',f:'3 dias/sem',tg:['Iniciante','Casa'],d:'Só o peso do corpo.',days:[D('A · Corpo inteiro','Agachamento livre 3x15;Flexão de braço 3x10;Afundo 3x12;Ponte de glúteo 3x15;Abdominal 3x20'),D('B · Superior e Core','Flexão de braço 4x10;Mergulho no banco 3x12;Abdominal bicicleta 3x20;Elevação de pernas 3x12'),D('C · Pernas e Glúteos','Agachamento búlgaro 3x10;Passada 3x12;Ponte de glúteo 4x15;Elevação de panturrilha 4x20')]},
{t:'Em Casa com Halteres',f:'2 a 3 dias/sem',tg:['Intermediário','Casa'],d:'Halteres e, se tiver, elástico.',days:[D('A · Superior','Supino com halteres 4x10;Remada unilateral 4x10;Desenvolvimento com halteres 3x10;Rosca direta 3x12;Tríceps francês 3x12'),D('B · Inferior','Agachamento livre 4x12;Stiff 3x12;Afundo 3x10;Hip thrust 3x12;Elevação de panturrilha 4x20')]},
{t:'Core e Abdômen (20 min)',f:'2 a 4 dias/sem',tg:['Iniciante','Casa','Academia'],d:'Treino curto de abdômen e lombar. Na prancha, as repetições são segundos.',days:[D('Core','Abdominal 3x20;Elevação de pernas 3x15;Prancha 3x30;Abdominal bicicleta 3x20;Hiperextensão lombar 3x12')]},
{t:'Braços e Ombros',f:'2 dias/sem',tg:['Intermediário','Academia'],d:'Complemento de volume para braços e ombros.',days:[D('A · Bíceps e Ombros','Rosca direta 4x10;Rosca martelo 3x12;Desenvolvimento com halteres 4x10;Elevação lateral 4x15;Encolhimento 3x12'),D('B · Tríceps e Ombros','Tríceps testa 4x10;Tríceps corda 3x12;Mergulho nas paralelas 3x10;Face pull 4x15;Elevação lateral 3x15')]},
{t:'Costas e Postura',f:'2 dias/sem',tg:['Iniciante','Academia'],d:'Fortalece costas, lombar e abdômen.',days:[D('Costas e Core','Puxada frontal 3x12;Remada baixa 3x12;Face pull 3x15;Hiperextensão lombar 3x12;Abdominal 3x15')]},
{t:'Corpo Inteiro 30 min',f:'2 a 3 dias/sem',tg:['Iniciante','Academia'],d:'Circuito rápido para dias corridos.',days:[D('Circuito','Agachamento livre 3x12;Flexão de braço 3x10;Remada curvada 3x10;Afundo 2x10;Abdominal 3x15')]},
{t:'Força 5x5',f:'3 dias/sem',tg:['Avançado','Academia'],d:'Poucos exercícios pesados, alternando A e B.',days:[D('A','Agachamento livre 5x5;Supino reto 5x5;Remada curvada 5x5'),D('B','Agachamento livre 5x5;Desenvolvimento militar 5x5;Levantamento terra 1x5')]}];
const nmP=(x,d)=>x.t+' · '+d[0],hasP=n=>S.plans.some(p=>p.name==n);
const FIL=['Todos','Iniciante','Intermediário','Avançado','Academia','Casa'];
const lib=()=>`<h2 class=mt style="margin-bottom:10px">Modelos de treino</h2><div class="row chips">${FIL.map(f=>`<span class="ch ${(tq||'Todos')==f?'on':''}" onclick="G.tg('${f=='Todos'?'':f}')">${f}</span>`).join('')}</div><div class=g2>${TPL.filter(x=>!tq||x.tg.includes(tq)).map(x=>{const i=TPL.indexOf(x);return`<div class=c><div class=sh><b class=f>${x.t}</b><span class=bd>${x.f}</span></div><p class=s>${x.d}</p><div class=row style="margin:8px 0">${x.tg.map(t=>`<span class=bd><i style="background:var(--ac2)"></i>${t}</span>`).join('')}</div>${x.days.map((d,j)=>`<div class=r><div class=f><b>${d[0]}</b><div class=s>${d[1].map(e=>e.n+' '+e.s+'×'+e.r).join(' · ')}</div></div>${hasP(nmP(x,d))?'<span class=s>Adicionada</span>':`<button class="b g sm" onclick="G.ad(${i},${j})">${UI.i('plus')}</button>`}</div>`).join('')}<button class="b mt" onclick="G.ad(${i},-1)">Adicionar semana inteira</button></div>`}).join('')}</div>`;
const trn=()=>`${UI.h('Treinos',UI.pb('A.pn()','Ficha'))}<div class=g2>${S.plans.map(p=>`<div class=c><div class=sh><b class=f>${esc(p.name)}</b>${UI.ib(`A.pe('${p.id}')`,'edit','Editar ficha')}</div>${p.ex.map(e=>{const l=last(e.n);return`<div class=r><span class=f>${esc(e.n)} <span class=s>${e.s}×${e.r}</span></span><span class=s>${l?'últ. '+top(l)+'kg':''}</span></div>`}).join('')}<button class="b mt" onclick="A.ws('${p.id}')">${UI.i('play')}Começar</button></div>`).join('')||UI.em('dumbbell','Crie sua primeira ficha.')}</div>${lib()}`;

const xlist=()=>{const L=allNames().filter(n=>nm(n).includes(nm(xq))&&(!xf||grp(n)==xf));return L.map(n=>{const l=last(n),g=grp(n);return`<div class=r><div class=f>${esc(n)}<div class=s>${g?LB[g]:'Sem grupo'}</div></div><span class=s>${l?fdt(l.date)+' · '+top(l)+'kg':''}</span></div>`}).join('')||UI.em('search','Nenhum exercício encontrado.')};
const exe=()=>`${UI.h('Exercícios')}<div class=sb>${UI.i('search')}<input placeholder="Buscar exercício" value="${esc(xq)}" oninput="G.q(this.value)"></div><div class="row chips"><span class="ch ${xf?'':'on'}" onclick="G.f('')">Todos</span>${Object.keys(LB).map(g=>`<span class="ch ${xf==g?'on':''}" onclick="G.f('${g}')">${LB[g]}</span>`).join('')}</div><div class=c id=xl>${xlist()}</div>`;

function prs(){return names().map(n=>{const h=hist(n);if(!h.length)return null;let b=null;h.forEach(x=>x.sets.forEach(s=>{if(!b||+s.l>b.l)b={l:+s.l,r:s.r,date:x.date}}));return b&&b.l>0?{n,...b}:null}).filter(Boolean).sort((a,b)=>b.date.localeCompare(a.date))}
const vol=(g,a,b)=>S.workouts.filter(w=>dd(w.date)>=a&&dd(w.date)<b).reduce((t,w)=>t+w.ex.filter(e=>grp(e.n)==g).reduce((u,e)=>u+e.sets.reduce((v,s)=>v+s.l*s.r,0),0),0);
const pro=()=>{const ns=[...new Set(S.workouts.flatMap(w=>w.ex.filter(e=>e.sets.length).map(e=>e.n)))],sel=ns.includes(px)?px:ns[0],ev=sel?hist(sel).map(h=>[h.date,top(h)]):[],gs=Object.keys(LB).map(g=>[g,vol(g,0,7),vol(g,7,14)]).filter(x=>x[1]||x[2]),mx=Math.max(1,...gs.map(x=>Math.max(x[1],x[2])));
return`${UI.h('Progresso')}<div class=g2><div class=c>${UI.ct('Evolução de carga')}${ns.length?`<select onchange="G.p(this.value)">${ns.map(n=>`<option${n==sel?' selected':''}>${esc(n)}</option>`).join('')}</select>${chart(ev.map(x=>x[1]),ev.map(x=>fdt(x[0])),1)}`:UI.em('chart','Aparece após o primeiro treino.')}</div>
<div class=c>${UI.ct('Recordes pessoais')}${prs().map(p=>`<div class=r><span class=f>${esc(p.n)}</span><b>${p.l}kg × ${p.r}</b><span class=s>${fdt(p.date)}</span></div>`).join('')||UI.em('target','Sem recordes ainda.')}</div>
<div class=c>${UI.ct('Volume por grupo (7 dias vs. 7 anteriores)')}${gs.map(x=>`<div class=sj><div class=sh><b class=f>${LB[x[0]]}</b><span class=s>${x[1]} vs ${x[2]} kg</span></div><div class=bar><i style="width:${x[1]/mx*100}%"></i></div></div>`).join('')||UI.em('chart','Sem treinos com grupo muscular reconhecido.')}</div>
<div class=c>${UI.ct('Histórico')}${S.workouts.slice().reverse().map(w=>`<div class="r top"><div class=f><b>${esc(w.name)}</b> <span class=s>${fdt(w.date)} · ${fd(w.sec)}</span>${w.ex.map(e=>`<div class=s>${esc(e.n)}: ${sets(e.sets)||'—'}</div>`).join('')}</div>${UI.ib(`A.wd('${w.id}')`,'x','Apagar treino')}</div>`).join('')||UI.em('clock','Nenhum treino registrado.')}</div></div>`};

const per=()=>{const un=names().filter(n=>!grp(n));return`${UI.h('Perfil')}<div class=g2><div class=c>${UI.ct('Descanso e avisos')}<label>Descanso padrão (segundos)<input type=number min=10 value=${S.rest} onchange="S.rest=+this.value||90;sv()"></label><button class=b onclick="A.nt()">${UI.i('bell')}Avisos de descanso</button></div>
<div class=c>${UI.ct('Exercícios sem grupo muscular')}${un.map((n,i)=>`<label>${esc(n)}<select onchange="G.as(${i},this.value)"><option value="">Escolher grupo…</option>${Object.keys(LB).map(g=>`<option value=${g}>${LB[g]}</option>`).join('')}</select></label>`).join('')||'<p class=s>Todos os seus exercícios têm grupo associado.</p>'}</div>
<div class=c>${UI.ct('Sincronização')}<p class=s>Os dados da Academia sincronizam junto com o resto do Hub.</p><button class="b g mt" onclick="go('cfg')">Dispositivos</button></div></div>`};

const act=()=>{const a=S.active;return`${UI.h(esc(a.name),`<button class="b g sm" onclick="A.nt()">${UI.i('bell')}Avisos</button>`)}<div class=rest>${UI.i('clock')}<span id=rs>Descanso: pronto</span></div><div class=g2>${a.ex.map((e,i)=>{const L=last(e.n);return`<div class=c>${UI.ct(esc(e.n)+` <span class=s>${e.s}×${e.r}</span>`)}<p class="s lh">${L?'Última sessão ('+fdt(L.date)+'): '+sets(L.sets):'Sem sessão anterior.'}</p>${e.sets.map((x,j)=>{const p=L&&L.sets[j],df=p?x.l-p.l:null;return`<div class=r><span class=f>Série ${j+1}</span><span>${x.l} kg × ${x.r} reps</span>${df==null?'':`<span class=s style="color:${df>0?'var(--ok)':df<0?'var(--er)':''}">${df>0?'+':''}${df} kg</span>`}</div>`}).join('')}<div class="row mt"><input id=l${i} type=number placeholder="${L&&L.sets[e.sets.length]?L.sets[e.sets.length].l+' kg':'kg'}" class=in-s><input id=r${i} type=number placeholder="reps" value=${e.r} class=in-s><button class="b sm" onclick="A.gs(${i})">${UI.i('check')}Concluir série</button></div></div>`}).join('')}</div><div class="row mt"><button class=b onclick="A.wf()">Finalizar treino</button><button class="b g" onclick="A.wc()">Cancelar</button></div>`};

const V={ini,trn,exe,pro,per};
P.gym=()=>S.active?act():`<div class=gy>${`<div class=gn>${TABS.map(t=>`<button class="${gt==t[0]?'on':''}" onclick="G.t('${t[0]}')" aria-label="${t[2]}">${UI.i(t[1])}<span>${t[2]}</span></button>`).join('')}</div>`}${V[gt]()}<div class=gsp></div></div>`;

window.G={t(x){gt=x;render();scrollTo(0,0)},v(x){gv=x;render()},m(g){gm=gm==g?null:g;render()},q(v){xq=v;$('#xl').innerHTML=xlist()},f(g){xf=g;render()},p(v){px=v;render()},
tg(x){tq=x;render()},ad(a,b){const x=TPL[a],ds=b<0?x.days:[x.days[b]];let n=0;ds.forEach(d=>{const nme=nmP(x,d);if(hasP(nme))return;S.plans.push({id:uid(),name:nme,ex:d[1].map(e=>({...e}))});n++});toast(n?n+' ficha(s) adicionada(s) em Treinos':'Já estavam nas suas fichas');RD()},as(i,v){const n=names().filter(n=>!grp(n))[i];if(!n||!v)return;const g=Object.assign({map:{}},S.use.gym);g.map=Object.assign({},g.map,{[n]:v});S.use=Object.assign({},S.use,{gym:g});RD()}};

const st=document.createElement('style');st.textContent=`
.bw{display:flex;justify-content:center;gap:8px}.bv{width:100%;max-width:210px;height:auto}
.bb{fill:var(--card);stroke:var(--bd);stroke-width:.8}
.mz{cursor:pointer;outline:0}.mz path{fill:var(--rs);stroke:var(--bd);stroke-width:.6;transition:fill .15s}
.mz.rec path{fill:var(--wa)}.mz.ok path{fill:var(--ac)}.mz.idle path{fill:var(--bd)}
.mz:hover path{filter:brightness(1.25)}.mz:focus-visible path,.mz.sel path{stroke:var(--tx);stroke-width:1.4}
.lg{display:flex;flex-wrap:wrap;gap:6px 14px;font-size:12px;color:var(--t2);margin-top:10px}.lg i{display:inline-block;width:9px;height:9px;border-radius:3px;margin-right:6px;background:var(--rs);border:1px solid var(--bd)}
.lg .r{background:var(--wa)}.lg .k{background:var(--ac)}.lg .d{background:var(--bd)}
.dt{fill:none;stroke:var(--bd);stroke-width:.5;pointer-events:none}.bt{justify-content:center;margin-bottom:6px}.hero .s{font-weight:500}.big2{height:44px;font-size:15px;width:100%}.lh{margin:-4px 0 8px}
.gn{display:flex;gap:4px;margin-bottom:16px;border-bottom:1px solid var(--bd);padding-bottom:10px}
.gn button{display:flex;align-items:center;gap:8px;padding:8px 14px;border:0;border-radius:8px;background:transparent;color:var(--t2);font:inherit;font-weight:500;cursor:pointer}
.gn button:hover{background:var(--hv);color:var(--tx)}.gn button.on{background:var(--hv);color:var(--tx);font-weight:600}.gn button.on .i{color:var(--ac2)}
.gsp{display:none}
@media(min-width:900px){.bt{display:none}.bv{max-width:190px}}
@media(max-width:899px){.bv:not(.on){display:none}.bv{max-width:230px}}
@media(max-width:760px){.gn{position:fixed;left:0;right:0;bottom:calc(64px + env(safe-area-inset-bottom,0px));z-index:4;margin:0;padding:4px;justify-content:space-around;background:var(--bg2);border:0;border-top:1px solid var(--bd)}
.gn button{flex:1;flex-direction:column;gap:2px;padding:6px 0;font-size:11px;min-width:0}.gn button.on{background:none}.gsp{display:block;height:64px}}`;
document.head.appendChild(st);
})();